### ISSUE TITLE
Code example incorrect in starlight-og-images.mdx

### ISSUE THREAD

**Issue by 3DRX** [HiDeoo/hideoo.dev#33]
### Describe the bug

![image](https://github.com/user-attachments/assets/bed0dd5c-7181-4d91-a653-af19b24962d7)

### To Reproduce

(content error)

### Expected behavior

![image](https://github.com/user-attachments/assets/bed0dd5c-7181-4d91-a653-af19b24962d7)

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your feedback.

Could you provide a little bit more information/context about the issue or avoid screenshots as they are not very helpful to spot the issue. In fact, I cannot even spot a difference between the image used in the "Describe the bug" section and the one from the "Expected behavior" section.
